# Generated by Django 5.2.4 on 2025-08-17 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MaxValueValidator(13)]),
        ),
    ]
