# Generated by Django 5.2.4 on 2025-08-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'permissions': [('view history', 'can view history')]},
        ),
    ]
