# Generated by Django 5.2.4 on 2025-08-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
