version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - SQL_USER=postgres
      - SQL_PASSWORD=postgrespassword
      - SQL_DB=postgresdb
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=postgresdb
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d postgresdb"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10s
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    # depends_on:
    #   db:
    #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/login?next=%2F"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
