# Generated by Django 5.2.4 on 2025-08-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='content_Type',
            new_name='content_type',
        ),
    ]
